---
# Configure a compute instance to run Cassandra

 - hosts: all
   user:  root

   vars:
    ansible_ssh_port: 2222
    ansible_ssh_user: root
    ssh_port: 2222

   roles:
    - vagrant
    - packages
    - java
    - cassandra
