# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = 'vvvv'
    ansible.playbook = 'bootstrap.yml'
    ansible.host_key_checking = false
    ansible.extra_vars = 'extra_vars.yml'
  end  
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end  
end
