# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

INSTANCE_COUNT = 4

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.provider :digital_ocean do |provider, override|
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    override.ssh.port=2222

    provider.client_id = 'DiM4NplqddalnQlgWmHWP'
    provider.api_key = 'e4a4dd4b5110dce4abbaaec7039b4e2c'
    provider.image = 'BaseImage'
    provider.region = 'New York 2'
  end

  (1..INSTANCE_COUNT).each do |id|
    name = sprintf "nk%02d", id

    config.vm.define "#{name}" do |host|
      host.vm.hostname = name

      host.vm.provision "ansible" do |ansible|
        ansible.playbook = 'bootstrap.yml'
        ansible.host_key_checking = false
        ansible.extra_vars = {
          fqdn: "{name}.netkernelroc.org"
        }
      end    
    end
  end
end
