require 'vagrant-openstack-plugin'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"
  config.ssh.private_key_path = "openstack_rsa"
  config.ssh.username = "ubuntu"

  config.vm.provider :openstack do |os|
    os.username = "metis"
    os.api_key = "metis"
    os.flavor = /m1.medium/
    os.image = /ubuntu-12.04.3/
    os.endpoint = "http://172.16.20.101:5000/v2.0/tokens"
    os.keypair_name = "vagrant"
    os.ssh_username = "ubuntu"
  end

end
